package automation.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import automation.utility.BaseClass;
import  automation.utility.Commons;

public class HolidaysTest extends BaseClass{
 
  @Test(groups = "H")
  public void holidaysCRUD() {
	String listofholidays="admin/masterdata/holiday/view";
	
    Commons.click(driver,By.xpath("//a[@href='#/admin/masterdata']"));
   
    Commons.click(driver,By.id(listofholidays));
    Commons.click(driver,By.id("Create"));
    
  
    Commons.enter(driver,By.id("holidayName"),data);
    Commons.enter(driver,By.id("holidayDesc"),data);
    Commons.enter(driver,By.id("holidayDate"),"12/27/2021");
    Commons.dropdown(driver,By.id("locationCode"));
        
    
    Commons.create(driver);
	Commons.filter(driver, By.id("holidayName"), data);
	

	Commons.edit(driver,data+1,By.id("holidayName"));
	Commons.filter(driver, By.id("holidayName"), data+1);
	
	Commons.activate(driver);
	Commons.edit(driver,data+2,By.id("holidayName"));
	Commons.filter(driver, By.id("holidayName"), data+2);
	Commons.deactivate(driver);

    }
}
