package io.mosip.testrig.adminui.testcase;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.testrig.adminui.kernel.util.ConfigManager;
import io.mosip.testrig.adminui.utility.BaseClass;
import io.mosip.testrig.adminui.utility.Commons;
import io.mosip.testrig.adminui.utility.JsonUtil;

public class BlockListTest extends BaseClass {

	@Test(groups = "BL")
	public void blocklistedwordsCRUD() {

		try {
			String blocklistedWord=ConfigManager.getdummyData();
		
			test=extent.createTest("BlockListTest", "verify Login");
		String idBlocklisted="admin/masterdata/blocklisted-words/view";
		Commons.click(test,driver, By.xpath("//a[@href='#/admin/masterdata']"));
		
		Commons.click(test,driver, By.id(idBlocklisted));

		Commons.click(test,driver, By.id("Create")); 
		test.log(Status.INFO, "Click on Create");
		Commons.enter(test,driver, By.id("word"), blocklistedWord); 
		Commons.enter(test,driver, By.id("description"), data);
   
		
		Commons.create(test,driver);
		test.log(Status.INFO, "Click on Create");
		Commons.filter(test,driver, By.id("word"), blocklistedWord);
		

		Commons.edit(test,driver,blocklistedWord+"auto",By.id("word"));
		test.log(Status.INFO, "Click on Edit");
		Commons.filter(test,driver, By.id("word"), blocklistedWord+"A");
		
		Commons.activate(test,driver);
		Commons.edit(test,driver,blocklistedWord+"B",By.id("word"));
		Commons.filter(test,driver, By.id("word"), blocklistedWord+"B");
		Commons.deactivate(test,driver);
		test.log(Status.INFO, "Click on Deactivate");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
