package io.mosip.testrig.adminui.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.apache.log4j.Logger;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.testrig.adminui.kernel.util.ConfigManager;
import io.mosip.testrig.adminui.utility.BaseClass;
import io.mosip.testrig.adminui.utility.Commons;
import io.mosip.testrig.adminui.utility.JsonUtil;
import io.mosip.testrig.adminui.utility.TestRunner;

public class LoginTest extends BaseClass{
	private static final Logger logger = Logger.getLogger(LoginTest.class);

 
  @Test(priority = 0)
  public void loginTest() throws Exception {
	  String envPath = System.getProperty("path");
	  String userid = System.getProperty("userid");
	  String password = System.getProperty("password");
	  String language = null;
    driver.get(envPath);
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
    driver.findElement(By.linkText("Admin")).click();
    
    try {
		 language=JsonUtil.JsonObjArrayListParsing2(ConfigManager.getlangcode());
	
    logger.info(language);
    } catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    
    Commons.click(test,driver,By.xpath("//*[@class='kc-dropdown']"));
    String var="//*[@class='kc-dropdown-item']/a[contains(text(),'"+language+"')]";
    Commons.click(test,driver,By.xpath(var));
    driver.findElement(By.id("username")).sendKeys(userid);
    driver.findElement(By.id("password")).sendKeys(password);
    driver.findElement(By.xpath("//input[@name=\'login\']")).click();
 
    /*
    Commons.click(test,driver,By.xpath("//a[@href='#/admin/masterdata']"));
   
    Commons.click(test,driver,By.xpath("//mat-card-content/span[contains(text(),'Blocklisted Words')]"));
    Commons.click(test,driver,By.xpath("//span[contains(text(),'Create')]"));
    String data=Commons.appendDate;
  
    Commons.enter(test,driver,By.xpath("//input[@placeholder='Blocklisted Words']"),data);
    Commons.enter(test,driver,By.xpath("//textarea[@placeholder='Description']"),data);
    
 
    Commons.click(test,driver,By.xpath("//button[@id='createButton']"));
    Commons.click(test,driver,By.xpath("//span[contains(text(),'OK')]")); 
    
    Commons.click(test,driver,By.xpath("//span[contains(text(),'Filter')]")); 
   
    Commons.enter(test,driver,By.xpath("//input[@placeholder=' Blocklisted Words']"),data);

    Commons.click(test,driver,By.xpath("//span[contains(text(),'Apply')]")); 
    
    Commons.click(test,driver,By.cssSelector(".ellipsis-button"));
    
    
    Commons.click(test,driver,By.xpath("//span[contains(text(),'Activate')]"));

    Commons.click(test,driver,By.xpath("//span[contains(text(),'Confirm')]"));

    Commons.click(test,driver,By.xpath("//span[contains(text(),'Done')]"));    
    
   driver.findElement(By.cssSelector(".ellipsis-button")).click();
    
    Commons.click(test,driver,By.xpath("//span[contains(text(),'Edit')]"));    

    Assert.assertNotEquals(data, driver.findElement(By.xpath("//input[@placeholder='Blocklisted Words']")).getText());
    driver.findElement(By.xpath("//input[@placeholder='Blocklisted Words']")).clear();
    
    Commons.enter(test,driver,By.xpath("//input[@placeholder='Blocklisted Words']"),data+1);
    
    Commons.click(test,driver,By.id("createButton")); 


    Commons.click(test,driver,By.xpath("//button/span[contains(text(),'OK')]")); 

    Commons.click(test,driver,By.xpath("//span[contains(text(),'Filter')]")); 
    Commons.enter(test,driver,By.xpath("//input[@placeholder='Blocklisted Words']"),data+1);
     Commons.click(test,driver,By.xpath("//span[contains(text(),'Apply')]")); 
    
    Commons.click(test,driver,By.cssSelector(".ellipsis-button"));
    Commons.click(test,driver,By.xpath("//span[contains(text(),'Deactivate')]"));
    
    Commons.clickSpan(driver,"Confirm");
    Commons.clickSpan(driver,"Done");
    
    */
  }
}
